name: aeroedge-agilerl
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - cryptography
  - pip:
      - aiohttp>=3.11.14
      - agilerl>=2.7.1
      - gymnasium>=1.0.0
      - numpy>=2.0.0,<3.0
      - pandas>=2.2.3
      - pettingzoo>=1.23.1
      - pytest
      - ruff
      - torch
      - websockets>=12
